version: '3.3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: embea
      MYSQL_USER: root
      MYSQL_PASSWORD: root